# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: aee21263f578ee1b0eaa7aa5b08be9a9e2c5eeae583279e988e95da05a2768f9804e70ebd508fab6151d6294dc48999a5f60ded7da0e4326b7792e5ecd8d8bfc

test:
  secret_key_base: 0cd3c26fdfcdd921192b4f39cd54a1fcb10bb7e2fb5b0ea07d43b6535d7ca4a0a1be68981d67dd0d0551c52c7039815aab48df5e66ff5ae590ccb618eb7c13c3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
